# Introduction to Tensorflow 2.0

In this notebook we are going to cover the fundamentals concepts of tensor using TensorFlow 2.0.


What is a tensor?
A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes.


What is TensorFlow?
TensorFlow is an open source software library for numerical computation using data flow graphs. Nodes in the graph represent mathematical operations, while the graph edges represent the multidimensional data arrays (tensors) communicated between them. The flexible architecture allows you to deploy computation to one or more CPUs or GPUs in a desktop, server, or mobile device with a single API. TensorFlow was originally developed by researchers and engineers working on the Google Brain team within Google's Machine Intelligence research organization for the purposes of conducting machine learning and deep neural networks research, but the system is general enough to be applicable in a wide variety of other domains as well.



Concepts covered in this notebook
* Introduction to Tensor
* Getting information from tensors
* Manipulating tensors
* Tensors and Numpy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try for yourself!

# Introduction to tensors

In [1]:
# Import TensorFlow and other libraries
import tensorflow as tf
import numpy as np
import pandas as pd

# Check the version of TensorFlow and other libraries
print("TensorFlow version: ", tf.__version__)
print("NumPy version: ", np.__version__)
print("Pandas version: ", pd.__version__)

TensorFlow version:  2.12.0
NumPy version:  1.23.5
Pandas version:  1.5.3


In [2]:
# creating tensors with tf.constant()

scalar = tf.constant(10)

# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
ndim = scalar.ndim

print("Scalar: ", scalar)
print("Number of dimensions: ", ndim)

Scalar:  tf.Tensor(10, shape=(), dtype=int32)
Number of dimensions:  0


In [3]:
# Create a vector (more than 1 dimension)

vector = tf.constant([10, 10])

# Check the dimension of our vector
ndim = vector.ndim

print("Vector: ", vector)
print("Number of dimensions: ", ndim)

Vector:  tf.Tensor([10 10], shape=(2,), dtype=int32)
Number of dimensions:  1


In [4]:
# Create a matrix (has more than one dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])

# Check the dimension of our matrix
ndim = matrix.ndim

print("Matrix: ", matrix)
print("Number of dimensions: ", ndim)

Matrix:  tf.Tensor(
[[10  7]
 [ 7 10]], shape=(2, 2), dtype=int32)
Number of dimensions:  2


In [5]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) # specify the data type with dtype parameter

# Check the dimension of our matrix
ndim = another_matrix.ndim

print("Matrix: ", another_matrix)
print("Number of dimensions: ", ndim)

Matrix:  tf.Tensor(
[[10.  7.]
 [ 3.  2.]
 [ 8.  9.]], shape=(3, 2), dtype=float16)
Number of dimensions:  2


In [6]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3, 4],
                       [5, 6, 7, 8],
                       [9, 10, 11, 12]],

                      [[13, 14, 15, 16],
                       [17, 18, 19, 20],
                       [21, 22, 23, 24]],

                      [[25, 26, 27, 28],
                       [29, 30, 31, 32],
                       [33, 34, 35, 36]]])

# Check the dimension of our tensor
ndim = tensor.ndim

print("Tensor: ", tensor)
print("Number of dimensions: ", ndim)

Tensor:  tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]], shape=(3, 3, 4), dtype=int32)
Number of dimensions:  3


In [7]:
# now use pandas to print the same information
df = pd.DataFrame({"Shape": [scalar.shape, vector.shape, matrix.shape, another_matrix.shape, tensor.shape],
                   "dimensions": [scalar.ndim, vector.ndim, matrix.ndim, another_matrix.ndim, tensor.ndim],
                   "Data type": [scalar.dtype, vector.dtype, matrix.dtype, another_matrix.dtype, tensor.dtype]},
                  index=["Scalar", "Vector", "Matrix", "Another matrix", "Tensor"])

df

Shape  dimensions           Data type
Scalar                 ()           0    <dtype: 'int32'>
Vector                (2)           1    <dtype: 'int32'>
Matrix             (2, 2)           2    <dtype: 'int32'>
Another matrix     (3, 2)           2  <dtype: 'float16'>
Tensor          (3, 3, 4)           3    <dtype: 'int32'>

## Summary so far
* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

### Creating tensors with `tf.Variable`

In [8]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10,7])

print("Changeable tensor: ", changeable_tensor)
print("Unchangeable Tensor: ",unchangeable_tensor)

Changeable tensor:  <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>
Unchangeable Tensor:  tf.Tensor([10  7], shape=(2,), dtype=int32)


In [9]:
# let's try to change the element in out changeable tensor
changeable_tensor[0].assign(1)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 7], dtype=int32)>

In [10]:
# Let's try to assign our unchangeable tensor
# unchangeable_tensor[0].assign[1]

# This will result in error as tensor created using tf.constant can not be changed later on in the code.

🔑 Note: it will be rare that you will have to decided weather to use tf.Variable or tf.constant to create a tensor as Tensorflow will do this for you. If you need to decide what to use, then it is safe to go with tf.donstant to prevent accidentally modifying the tensor later on in the code without realization which might cause trouble.

##  Create Random Tensor

As the name suggest, these are tensor of some size with random number.

In [11]:
# let's create two random (but the same) tensor

random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape = (5,3))

random_2 =  tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (5,3))

print("Random tensor 1: ", random_1)
print()
print("Random tensor 2: ", random_2)

# Are they equal?
random_1 == random_2

# use if/else to check if they are equal
random_1 == random_2

Random tensor 1:  tf.Tensor(
[[-0.7565803  -0.06854702  0.07595026]
 [-1.2573844  -0.23193763 -1.8107855 ]
 [ 0.09988727 -0.50998646 -0.7535805 ]
 [-0.57166284  0.1480774  -0.23362993]
 [-0.3522796   0.40621263 -1.0523509 ]], shape=(5, 3), dtype=float32)

Random tensor 2:  tf.Tensor(
[[-0.7565803  -0.06854702  0.07595026]
 [-1.2573844  -0.23193763 -1.8107855 ]
 [ 0.09988727 -0.50998646 -0.7535805 ]
 [-0.57166284  0.1480774  -0.23362993]
 [-0.3522796   0.40621263 -1.0523509 ]], shape=(5, 3), dtype=float32)


<tf.Tensor: shape=(5, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>

In [12]:
# let's shuffle our random tensor
not_shuffled = tf.constant([[10, 7],
                             [3, 4],
                             [2, 5]])

# shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>